name: This And That
favicon: null
layout_spectrum: 1
typography_spectrum: 0.02072133542969823
title: This And That
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dde0e5'
    - '#68686a'
    - '#10130c'
    - '#404042'
    - '#bf9348'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
